apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerok8sdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zero-k8s-app
    spec:
      containers:
        - name: zero-wa4c-demo
          image: zeroacrdemo.azurecr.io/azure-bootcamp-zerodemo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: zero-k8s-app
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: 80
  selector:
    app: zero-k8s-app
  type: LoadBalancer
